[package]
name    = "inotify-sys"
version = "0.1.2-dev"
authors = ["Hanno Braun <hb@hannobraun.de>"]

description   = "inotify bindings for the Rust programming language"
documentation = "https://docs.rs/inotify-sys"
repository    = "https://github.com/inotify-rs/inotify-sys"
license       = "ISC"
readme        = "README.md"

keywords   = ["inotify", "linux"]
categories = ["external-ffi-bindings", "filesystem"]

[badges]
travis-ci = { repository = "inotify-rs/inotify-sys" }

[dependencies]
libc = "0.2"

[package.metadata.release]
pre-release-commit-message = "Release {{version}}"
pro-release-commit-message = "Bump version to {{version}}"
tag-prefix                 = "v"
tag-message                = "Version {{version}}"
dev-version-ext            = "dev"
